//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERN028_MakinaVeriTopalamaFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachinesCycleTimeHistories
    {
        public int MachinesCycleTimeHistoryID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<System.DateTime> DayTime { get; set; }
        public string CycleTimeFormula { get; set; }
    }
}
