//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERN028_MakinaVeriTopalamaFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineProductionDatas
    {
        public int Id { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int ProductionCount { get; set; }
        public double CycleTime { get; set; }
        public int MachineID { get; set; }
    }
}
