//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERN028_MakinaVeriTopalamaFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineDowntimeReports
    {
        public int MachineDowntimeReportID { get; set; }
        public Nullable<System.DateTime> DownTime { get; set; }
        public Nullable<System.DateTime> DownEndTime { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> MachineFaultCategoriesID { get; set; }
        public string AdditionalFaultInfo { get; set; }
        public Nullable<int> MachineSolutionInfoCategoriesID { get; set; }
        public string AdditionalSolutionInfo { get; set; }
        public Nullable<int> employeeId { get; set; }
    }
}
