//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERN028_MakinaVeriTopalamaFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineHistoryStatus
    {
        public int MachineHistoryStatusID { get; set; }
        public Nullable<System.DateTime> DateDay { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<double> AverageCycleTime { get; set; }
        public Nullable<int> ProducedItems { get; set; }
        public Nullable<int> OKProductCount { get; set; }
        public Nullable<int> NGProductCoutn { get; set; }
        public Nullable<double> OKRatio { get; set; }
        public string CycleTimeFormula { get; set; }
    }
}
