//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERN028_MakinaVeriTopalamaFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineChangeLogs
    {
        public int ChangeLogID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<double> PreviousValue { get; set; }
        public Nullable<double> ChangeValue { get; set; }
    
        public virtual Machines Machines { get; set; }
    }
}
