//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERN028_MakinaVeriTopalamaFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineCurrentStatus
    {
        public int MachineCurrentStatusID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> StatusTypeID { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public Nullable<double> AverageCycleTime { get; set; }
        public Nullable<int> ProducedItems { get; set; }
        public Nullable<int> OKProductCount { get; set; }
        public Nullable<int> NGProductCount { get; set; }
        public Nullable<double> OKRatio { get; set; }
        public Nullable<int> CurrentDailyProduction { get; set; }
        public Nullable<int> MachineQueueNumber { get; set; }
        public Nullable<int> CurrentDailyOKProduction { get; set; }
        public Nullable<int> CurrentDailyNGProduction { get; set; }
        public Nullable<double> CalculatedCycleTime { get; set; }
    
        public virtual MachineStatusTypes MachineStatusTypes { get; set; }
        public virtual Machines Machines { get; set; }
    }
}
