//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERN028_MakinaVeriTopalamaFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Machines()
        {
            this.MachineChangeLogs = new HashSet<MachineChangeLogs>();
            this.MachineCurrentStatus = new HashSet<MachineCurrentStatus>();
        }
    
        public int MachineID { get; set; }
        public string MachineIdentifier { get; set; }
        public string IPAdresses { get; set; }
        public Nullable<int> FactoryPlantId { get; set; }
        public Nullable<int> LineId { get; set; }
        public Nullable<double> ExpectedCycleTime { get; set; }
        public Nullable<int> PortAdress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineChangeLogs> MachineChangeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineCurrentStatus> MachineCurrentStatus { get; set; }
    }
}
