//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERN028_MakinaVeriTopalamaFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineLossQualities
    {
        public int MachineLossQualityID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string FaultInfo { get; set; }
        public Nullable<int> MachineFaultTypeID { get; set; }
        public Nullable<int> LossQuantity { get; set; }
        public Nullable<System.DateTime> LossDate { get; set; }
        public Nullable<int> employeeId { get; set; }
    }
}
