//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERN028_MakinaVeriTopalamaFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineDowntimeReports
    {
        public int MachineDowntimeReportID { get; set; }
        public Nullable<System.DateTime> DownTimeDate { get; set; }
        public string MachineID { get; set; }
        public string FaultInfo { get; set; }
        public string SolutionInfo { get; set; }
        public Nullable<int> TimeForSolving { get; set; }
        public Nullable<int> Frequancy { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<int> employeeId { get; set; }
    }
}
